version: '3.8'
services:
  app:
    container_name: task-manager-app
    build: 
      context: ./task-manager-app
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - api
    ports:
      - "8080:80"
  api:
    container_name: task-manager-api
    build: 
      context: ./task-manager-api
      dockerfile: Dockerfile
    ports:
      - '3333:3333'
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=task-management
      - JWT_SECRET=jobsitycodechallenge2024
  postgres:
    container_name: task-manager-db
    image: postgres:13.5
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=task-management
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
 
volumes:
  postgres: