version: '3.8'
services:
  postgres:
    image: postgres:13.5
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=task-management
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  app:
    build: ./task-manager-api
    ports:
      - '3333:3333'
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=task-management
      - JWT_SECRET=jobsitycodechallenge2024
volumes:
  postgres: